import os
import sys
import uuid
from pathlib import Path
from stellar_sdk import Keypair

def print_banner():
    print("=" * 60)
    print("      🚀 Stellar x402 'Potato PC' Node Setup 🚀      ")
    print("=" * 60)
    print("This script will help you join the x402 network by:")
    print("1. Generating/Configuring your Executor accounts.")
    print("2. Setting up your .env file.")
    print("3. Registering your agent in the on-chain registry.")
    print("4. Setting up a local secrets vault for your agents.")
    print("=" * 60)

def main():
    print_banner()

    # 1. Check for existing .env
    env_path = Path(".env")
    if env_path.exists():
        confirm = input(".env already exists. Overwrite? (y/N): ").strip().lower()
        if confirm != 'y':
            print("Aborting setup to protect existing .env.")
            sys.exit(0)

    # 2. Gather Configuration
    print("\n--- 🔧 Step 1: Network Configuration ---")
    registry_contract_id = input("Enter REGISTRY_CONTRACT_ID (provided by network admin): ").strip()
    if not registry_contract_id:
        print("Error: REGISTRY_CONTRACT_ID is required to join the network.")
        sys.exit(1)

    public_base_url = input("Enter your PUBLIC_BASE_URL (e.g. http://your-ip:8000): ").strip()
    if not public_base_url:
        public_base_url = "http://localhost:8000"
        print(f"Defaulting to {public_base_url}")

    # 3. Handle Accounts
    print("\n--- 🔑 Step 2: Account Setup ---")
    gen_keys = input("Generate new EXECUTOR keys? (y/N): ").strip().lower()
    if gen_keys == 'y':
        kp = Keypair.random()
        executor_pk = kp.public_key
        executor_secret = kp.secret
        print(f"Generated Public Key: {executor_pk}")
        print(f"Generated Secret Key: {executor_secret}")
        print("⚠️  SAVE THIS SECRET! It won't be shown again.")
    else:
        executor_pk = input("Enter EXECUTOR_PUBLIC_KEY: ").strip()
        executor_secret = input("Enter EXECUTOR_SECRET: ").strip()

    # 4. Generate Agent ID
    agent_id = input(f"Enter an Agent ID for your node (default: agent_{uuid.uuid4().hex[:8]}): ").strip()
    if not agent_id:
        agent_id = f"agent_{uuid.uuid4().hex[:8]}"
    print(f"Your Agent ID: {agent_id}")

    # 5. Write .env
    print("\n--- 📝 Step 3: Writing .env ---")
    env_content = f"""# Stellar x402 Executor Configuration
# Generated by scripts/setup_node.py

# Accounts
EXECUTOR_PUBLIC_KEY={executor_pk}
EXECUTOR_SECRET={executor_secret}
DEPLOYER_PUBLIC_KEY={executor_pk}
DEPLOYER_SECRET={executor_secret}

# Registry
REGISTRY_CONTRACT_ID={registry_contract_id}
REGISTRY_BYPASS_DEV=false

# Networking
PUBLIC_BASE_URL={public_base_url}
HORIZON_URL=https://horizon-testnet.stellar.org
SOROBAN_RPC_URL=https://soroban-testnet.stellar.org

# Prices
X402_PRICE=0.01
X402_STELLAR_ASSET=USDC:G... # Replace with actual USDC issuer if needed

# Docker
DOCKER_ALLOWED_IMAGES=python:3.11-slim,node:20-slim,mcr.microsoft.com/playwright:v1.43.0-jammy
"""
    with open(".env", "w") as f:
        f.write(env_content)
    print("Successfully wrote .env file.")

    # 6. Create Secrets Dir
    print("\n--- 🔒 Step 4: Setting up Secrets Vault ---")
    secrets_dir = Path("secrets")
    secrets_dir.mkdir(exist_ok=True)
    agent_secret_file = secrets_dir / f"{agent_id}.env"
    if not agent_secret_file.exists():
        with open(agent_secret_file, "w") as f:
            f.write(f"# Secrets for {agent_id}\n# OPENAI_API_KEY=sk-...\n# ANTHROPIC_API_KEY=...\n")
        print(f"Created template secrets file: {agent_secret_file}")

    # 7. Add secrets to .gitignore
    gitignore_path = Path(".gitignore")
    if gitignore_path.exists():
        with open(gitignore_path, "r") as f:
            lines = f.readlines()
        if "secrets/\n" not in lines:
            with open(gitignore_path, "a") as f:
                f.write("\n# x402 Secrets\nsecrets/\n")
            print("Added secrets/ to .gitignore")

    # 8. Registry Registration Prompt
    print("\n--- 🌍 Step 5: On-Chain Registration ---")
    print(f"To finish, you need to register agent '{agent_id}' in the registry.")
    print("Fund your account first at: https://lab.stellar.org/#account-creator?network=testnet")
    confirm_reg = input("Attempt automatic registration now? (Requires funded account) (y/N): ").strip().lower()
    
    if confirm_reg == 'y':
        try:
            from scripts.registry_client import RegistryClient
            client = RegistryClient()
            print(f"Registering {agent_id}...")
            client.register_agent(agent_id, "ipfs://setup_node_auto", executor_secret)
            print("✅ Agent successfully registered on-chain!")
        except Exception as e:
            print(f"❌ Registration failed: {e}")
            print("You can try again later with: python scripts/registry_client.py")
    else:
        print("Skipping automatic registration.")

    print("\n" + "=" * 60)
    print("🎉 SETUP COMPLETE! 🎉")
    print(f"1. Put your API keys in secrets/{agent_id}.env")
    print("2. Run your node: docker compose up --build")
    print(f"3. Your agent URL: {public_base_url}/.well-known/x402")
    print("=" * 60)

if __name__ == "__main__":
    main()
